const navUrls = {
  home: "/",
  about: "/about-us",
  contact: "/contact-us",
  checkout: "/checkout",
  careers: "/careers",
  community: "/community",
  emi: "/emi",
  insurance: "/insurance",
  buySmart: "/buysmart",
  signIn: "/signin",
  signUp: "/signup",
  warranty: "/warranty",
  blog: "/blog",
  blogpost: "/blog-post",
  cart: "/cart",
  selectAddress: "/select-address",
  addAddresss: "/add-address",
  testride: "/book-test-ride",
  products: "/products",
  partner: "/partner-with-us",
  product: "/:productSlug",
  product_new: "/product/:productSlug",
};

export default navUrls;
